### ISSUE TITLE
USER STORY: Create a note

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-frontend#10]
* [ ] - #27 

As a **user** I can **create a note using my voice or by typing** so that I can **capture my thoughts quickly and efficiently**.

## Acceptance criteria
* User can write in a text form
* User can dictate into the form
* User receives visual feedback when the voice recognition component if listening.
* Save button to save the form content

## Tasks
- [x] Create text area component
- [x] Create voice recognition component
- [x] Create save button that send a post request to the API
