### ISSUE TITLE
USER STORY: View folders

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-frontend#17]
* [ ] - #28 

As a **user** I can **view a list of my folders** so that **I can see the notes inside of them**.

## Acceptance criteria
* Display list of a user's folders
* User can click on the folder to view the contained notes

## Tasks
- [x] Create Folders page
- [x] Map through folders state to show list of folder items
- [x] Create click handler that finds notes with the corresponding folder_id
