### ISSUE TITLE
USER STORY: Sign up & log in

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-frontend#19]
* [ ] - #30 

As a **user** I can **create an account and log in** so that **I can use the application**.

## Acceptance criteria
* Sign up form
* Log in form
* User can create an account with a username and password
* User can log in with that information and stay logged in until they log out on the device

## Tasks
- [x] Create sign up form
- [x] Save returned token to context
- [x] Create log in form
