### ISSUE TITLE
USER STORY: Search

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-frontend#26]
* [ ] - #34 

As a **user** I can **search for my notes and folders** so that **I can quickly and easily find them**.

## Acceptance criteria
* Search input form
* Search results display notes and folders, with headings
* Results dynamically filter as the user types
* User can click on notes and have CRUD capability

## Tasks
- [x] Create Search page
- [x] Filter Notes and Folders state with user input
- [x] Create message for when search returns no results
